language: "java"

script: "mvn -B clean install -Pqulice"

jdk:
    - "oraclejdk8"

cache:
  directories:
    - "$HOME/.m2"

after_success:
    - "bash <(curl -s https://codecov.io/bash)"
before_deploy:
    - "mkdir .bintray"
    - "wget -O .bintray/settnigs.xml https://gist.githubusercontent.com/g4s8/9b58037668e8dbbd86585cddb7ddf9b8/raw/b5c2f16c7fe5e4161ec7555628b69d14222ffbf3/bintray-settings.xml"

deploy:
  - provider: "script"
    skip_cleanup: true
    script: "mvn deploy --settings .bintray/settings.xml"
    on:
        branch: "master"
